---
title: "Graphique - Carte"
author: "Romane"
date: "23/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
volcano <- read_delim("volcano.csv",
                      delim = ";", 
                      escape_double = FALSE,
                      trim_ws = TRUE)
#names(volcano)
volcano$Year <- as.factor(volcano$Year)
volcano$Name <- as.factor(volcano$Name)
volcano$Location <- as.factor(volcano$Location)
volcano$Country <- as.factor(volcano$Country)

summary(volcano)
```


```{r}
world <- ne_countries(scale = "medium",
                      returnclass = "sf",
                      type = 'countries')
world %>% 
  ggplot() + 
  geom_sf()
```



```{r}
library(rnaturalearth)
library(ggplot2)
library(tidyverse)

world <- ne_countries(scale = "medium",
                      returnclass = "sf")
world %>% 
  ggplot() + 
  geom_sf() +
  geom_point(data = volcano,
             aes(x = Longitude,
                 y = Latitude,
                 size = TOTAL_COST,
                 color = TOTAL_COST,
                 text = Name),
             show.legend = FALSE,
             alpha = 0.8)

```


```{r}
library(cowplot)

try <- map_data('world')

ggplot() +
  geom_polygon(data = try,
               aes(x = long, y = lat, group = group),
               fill = 'grey') +
  geom_point(data = volcano %>% arrange(TOTAL_COST),
             aes(x = Longitude,
                 y = Latitude,
                 color = DAMAGE_MILLIONS_DOLLARS,
                 size = TOTAL_LIFE_COST),
             alpha = 0.8) +
  scale_color_gradientn(colors = c('#FF6600',
                                   '#330000'),
                        name = 'Coût en terme de vie') +
  scale_size(name = 'Coûts des dégats matériels') +
  coord_map('mercator',
            xlim = c(-180,180)) +
  theme_map() +
  theme(legend.position = 'bottom') +
  labs(title = 'Coût des eruptions dans le monde',
               subtitle = 'Coûts matériels et humains')
```
























